[build]
  functions = "netlify/functions"

[[redirects]]
  from   = "/extract"
  to     = "/.netlify/functions/extract"
  status = 200

[[redirects]]
  from   = "/site"
  to     = "/.netlify/functions/site"
  status = 200
